# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='Income',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='household',
            name='Lat',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='household',
            name='Lon',
            field=models.FloatField(max_length=25),
        ),
    ]
