# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170830_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('Relation', models.CharField(default='', max_length=15)),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Farmer')),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='household',
        ),
        migrations.AlterField(
            model_name='household',
            name='Income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='household',
            name='Lat',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='household',
            name='Lon',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.AddField(
            model_name='household',
            name='F_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Farmer'),
        ),
    ]
